"use strict";
var graphqlApi = require("./api/graphqlApi");
var bodyParser = require("body-parser");
var express = require("express");
var app = express();
var port = process.env.PORT || 3000;
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use("/graphql", graphqlApi);
app.listen(port, function () { return console.log("Listening on port " + port); });
